### ISSUE TITLE
can this be used to limit the whole server traffic rate?

### ISSUE THREAD

**Issue by auxten** [Laobei2012/Nginx-limit-traffic-rate-module#2]
can this be used to limit the whole server traffic rate?
if so, how?

**Comment by Laobei2012** [comment]
It's possible I think, if we set $host as the limit variable.

```
     limit_traffic_rate_zone   rate $host 32m;

     server {
         location /download/ {
             limit_traffic_rate  rate 20k;
         }
     }
```

All the requests with same header "Host" would be limited in total rate 20k.

BTW, if you want to control traffic in server level, tc may be a better 
solution.

# man tc

TC(8) Linux                                 TC(8)

NAME
        tc - show / manipulate traffic control settings

于 2012-12-19 16:28, auxten 写道:

**Comment by auxten** [comment]
thx, man
